In [77]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn import svm
from sklearn.metrics import accuracy_score

In [78]:
dt=pd.read_csv(r'C:\Users\ISHITA\OneDrive\Desktop\ALZHEIMERS_PREDICTION\alzheimers_disease_data.csv')

In [79]:
dt

PatientID  Age  Gender  Ethnicity  EducationLevel        BMI  Smoking  \
0          4751   73       0          0               2  22.927749        0   
1          4752   89       0          0               0  26.827681        0   
2          4753   73       0          3               1  17.795882        0   
3          4754   74       1          0               1  33.800817        1   
4          4755   89       0          0               0  20.716974        0   
...         ...  ...     ...        ...             ...        ...      ...   
2144       6895   61       0          0               1  39.121757        0   
2145       6896   75       0          0               2  17.857903        0   
2146       6897   77       0          0               1  15.476479        0   
2147       6898   78       1          3               1  15.299911        0   
2148       6899   72       0          0               2  33.289738        0   

      AlcoholConsumption  PhysicalActivity  DietQuality  ...  \
0              13.297218          6.327112     1.347214  ...   
1               4.542524          7.619885     0.518767  ...   
2              19.555085          7.844988     1.826335  ...   
3              12.209266          8.428001     7.435604  ...   
4              18.454356          6.310461     0.795498  ...   
...                  ...               ...          ...  ...   
2144            1.561126          4.049964     6.555306  ...   
2145           18.767261          1.360667     2.904662  ...   
2146            4.594670          9.886002     8.120025  ...   
2147            8.674505          6.354282     1.263427  ...   
2148            7.890703          6.570993     7.941404  ...   

      MemoryComplaints  BehavioralProblems       ADL  Confusion  \
0                    0                   0  1.725883          0   
1                    0                   0  2.592424          0   
2                    0                   0  7.119548          0   
3                    0                   1  6.481226          0   
4                    0                   0  0.014691          0   
...                ...                 ...       ...        ...   
2144                 0                   0  4.492838          1   
2145                 0                   1  9.204952          0   
2146                 0                   0  5.036334          0   
2147                 0                   0  3.785399          0   
2148                 0                   1  8.327563          0   

      Disorientation  PersonalityChanges  DifficultyCompletingTasks  \
0                  0                   0                          1   
1                  0                   0                          0   
2                  1                   0                          1   
3                  0                   0                          0   
4                  0                   1                          1   
...              ...                 ...                        ...   
2144               0                   0                          0   
2145               0                   0                          0   
2146               0                   0                          0   
2147               0                   0                          0   
2148               1                   0                          0   

      Forgetfulness  Diagnosis  DoctorInCharge  
0                 0          0       XXXConfid  
1                 1          0       XXXConfid  
2                 0          0       XXXConfid  
3                 0          0       XXXConfid  
4                 0          0       XXXConfid  
...             ...        ...             ...  
2144              0          1       XXXConfid  
2145              0          1       XXXConfid  
2146              0          1       XXXConfid  
2147              1          1       XXXConfid  
2148              1          0       XXXConfid  

[2149 rows x 35 columns]

In [80]:
dt.head()

PatientID  Age  Gender  Ethnicity  EducationLevel        BMI  Smoking  \
0       4751   73       0          0               2  22.927749        0   
1       4752   89       0          0               0  26.827681        0   
2       4753   73       0          3               1  17.795882        0   
3       4754   74       1          0               1  33.800817        1   
4       4755   89       0          0               0  20.716974        0   

   AlcoholConsumption  PhysicalActivity  DietQuality  ...  MemoryComplaints  \
0           13.297218          6.327112     1.347214  ...                 0   
1            4.542524          7.619885     0.518767  ...                 0   
2           19.555085          7.844988     1.826335  ...                 0   
3           12.209266          8.428001     7.435604  ...                 0   
4           18.454356          6.310461     0.795498  ...                 0   

   BehavioralProblems       ADL  Confusion  Disorientation  \
0                   0  1.725883          0               0   
1                   0  2.592424          0               0   
2                   0  7.119548          0               1   
3                   1  6.481226          0               0   
4                   0  0.014691          0               0   

   PersonalityChanges  DifficultyCompletingTasks  Forgetfulness  Diagnosis  \
0                   0                          1              0          0   
1                   0                          0              1          0   
2                   0                          1              0          0   
3                   0                          0              0          0   
4                   1                          1              0          0   

   DoctorInCharge  
0       XXXConfid  
1       XXXConfid  
2       XXXConfid  
3       XXXConfid  
4       XXXConfid  

[5 rows x 35 columns]

In [81]:
dt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2149 entries, 0 to 2148
Data columns (total 35 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   PatientID                  2149 non-null   int64  
 1   Age                        2149 non-null   int64  
 2   Gender                     2149 non-null   int64  
 3   Ethnicity                  2149 non-null   int64  
 4   EducationLevel             2149 non-null   int64  
 5   BMI                        2149 non-null   float64
 6   Smoking                    2149 non-null   int64  
 7   AlcoholConsumption         2149 non-null   float64
 8   PhysicalActivity           2149 non-null   float64
 9   DietQuality                2149 non-null   float64
 10  SleepQuality               2149 non-null   float64
 11  FamilyHistoryAlzheimers    2149 non-null   int64  
 12  CardiovascularDisease      2149 non-null   int64  
 13  Diabetes                   2149 non-null   int64

In [82]:
dt.isnull().sum()

PatientID                    0
Age                          0
Gender                       0
Ethnicity                    0
EducationLevel               0
BMI                          0
Smoking                      0
AlcoholConsumption           0
PhysicalActivity             0
DietQuality                  0
SleepQuality                 0
FamilyHistoryAlzheimers      0
CardiovascularDisease        0
Diabetes                     0
Depression                   0
HeadInjury                   0
Hypertension                 0
SystolicBP                   0
DiastolicBP                  0
CholesterolTotal             0
CholesterolLDL               0
CholesterolHDL               0
CholesterolTriglycerides     0
MMSE                         0
FunctionalAssessment         0
MemoryComplaints             0
BehavioralProblems           0
ADL                          0
Confusion                    0
Disorientation               0
PersonalityChanges           0
DifficultyCompletingTasks    0
Forgetfu

In [83]:
dt.describe()

PatientID          Age       Gender    Ethnicity  EducationLevel  \
count  2149.000000  2149.000000  2149.000000  2149.000000     2149.000000   
mean   5825.000000    74.908795     0.506282     0.697534        1.286645   
std     620.507185     8.990221     0.500077     0.996128        0.904527   
min    4751.000000    60.000000     0.000000     0.000000        0.000000   
25%    5288.000000    67.000000     0.000000     0.000000        1.000000   
50%    5825.000000    75.000000     1.000000     0.000000        1.000000   
75%    6362.000000    83.000000     1.000000     1.000000        2.000000   
max    6899.000000    90.000000     1.000000     3.000000        3.000000   

               BMI      Smoking  AlcoholConsumption  PhysicalActivity  \
count  2149.000000  2149.000000         2149.000000       2149.000000   
mean     27.655697     0.288506           10.039442          4.920202   
std       7.217438     0.453173            5.757910          2.857191   
min      15.008851     0.000000            0.002003          0.003616   
25%      21.611408     0.000000            5.139810          2.570626   
50%      27.823924     0.000000            9.934412          4.766424   
75%      33.869778     1.000000           15.157931          7.427899   
max      39.992767     1.000000           19.989293          9.987429   

       DietQuality  ...  FunctionalAssessment  MemoryComplaints  \
count  2149.000000  ...           2149.000000       2149.000000   
mean      4.993138  ...              5.080055          0.208004   
std       2.909055  ...              2.892743          0.405974   
min       0.009385  ...              0.000460          0.000000   
25%       2.458455  ...              2.566281          0.000000   
50%       5.076087  ...              5.094439          0.000000   
75%       7.558625  ...              7.546981          0.000000   
max       9.998346  ...              9.996467          1.000000   

       BehavioralProblems          ADL    Confusion  Disorientation  \
count         2149.000000  2149.000000  2149.000000     2149.000000   
mean             0.156817     4.982958     0.205212        0.158213   
std              0.363713     2.949775     0.403950        0.365026   
min              0.000000     0.001288     0.000000        0.000000   
25%              0.000000     2.342836     0.000000        0.000000   
50%              0.000000     5.038973     0.000000        0.000000   
75%              0.000000     7.581490     0.000000        0.000000   
max              1.000000     9.999747     1.000000        1.000000   

       PersonalityChanges  DifficultyCompletingTasks  Forgetfulness  \
count         2149.000000                2149.000000    2149.000000   
mean             0.150768                   0.158678       0.301536   
std              0.357906                   0.365461       0.459032   
min              0.000000                   0.000000       0.000000   
25%              0.000000                   0.000000       0.000000   
50%              0.000000                   0.000000       0.000000   
75%              0.000000                   0.000000       1.000000   
max              1.000000                   1.000000       1.000000   

         Diagnosis  
count  2149.000000  
mean      0.353653  
std       0.478214  
min       0.000000  
25%       0.000000  
50%       0.000000  
75%       1.000000  
max       1.000000  

[8 rows x 34 columns]

In [84]:
dt['Diagnosis'].value_counts()

Diagnosis
0    1389
1     760
Name: count, dtype: int64

In [85]:
dt.groupby('Diagnosis').mean(numeric_only=True)

PatientID        Age    Gender  Ethnicity  EducationLevel  \
Diagnosis                                                                
0          5806.177106  74.945284  0.514039   0.708423        1.316055   
1          5859.401316  74.842105  0.492105   0.677632        1.232895   

                 BMI   Smoking  AlcoholConsumption  PhysicalActivity  \
Diagnosis                                                              
0          27.515092  0.290137           10.071880           4.90764   
1          27.912670  0.285526            9.980156           4.94316   

           DietQuality  ...       MMSE  FunctionalAssessment  \
Diagnosis               ...                                    
0             4.974839  ...  16.265543              5.860669   
1             5.026581  ...  11.994657              3.653380   

           MemoryComplaints  BehavioralProblems       ADL  Confusion  \
Diagnosis                                                              
0                  0.115911            0.096472  5.707951   0.210943   
1                  0.376316            0.267105  3.657938   0.194737   

           Disorientation  PersonalityChanges  DifficultyCompletingTasks  \
Diagnosis                                                                  
0                0.164867            0.156228                   0.156228   
1                0.146053            0.140789                   0.163158   

           Forgetfulness  
Diagnosis                 
0               0.301656  
1               0.301316  

[2 rows x 33 columns]

separating features and target

In [86]:
x = dt.drop(columns=['Diagnosis','DoctorInCharge','Ethnicity'] ,axis=1).values
y=dt['Diagnosis'].values

In [87]:
x[0]

array([4.75100000e+03, 7.30000000e+01, 0.00000000e+00, 2.00000000e+00,
       2.29277492e+01, 0.00000000e+00, 1.32972177e+01, 6.32711247e+00,
       1.34721431e+00, 9.02567867e+00, 0.00000000e+00, 0.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       1.42000000e+02, 7.20000000e+01, 2.42366840e+02, 5.61508970e+01,
       3.36825635e+01, 1.62189143e+02, 2.14635324e+01, 6.51887697e+00,
       0.00000000e+00, 0.00000000e+00, 1.72588346e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00])

In [88]:
x

array([[4.751e+03, 7.300e+01, 0.000e+00, ..., 0.000e+00, 1.000e+00,
        0.000e+00],
       [4.752e+03, 8.900e+01, 0.000e+00, ..., 0.000e+00, 0.000e+00,
        1.000e+00],
       [4.753e+03, 7.300e+01, 0.000e+00, ..., 0.000e+00, 1.000e+00,
        0.000e+00],
       ...,
       [6.897e+03, 7.700e+01, 0.000e+00, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [6.898e+03, 7.800e+01, 1.000e+00, ..., 0.000e+00, 0.000e+00,
        1.000e+00],
       [6.899e+03, 7.200e+01, 0.000e+00, ..., 0.000e+00, 0.000e+00,
        1.000e+00]])

In [89]:
y

array([0, 0, 0, ..., 1, 1, 0], dtype=int64)

In [90]:
dt.corr

<bound method DataFrame.corr of       PatientID  Age  Gender  Ethnicity  EducationLevel        BMI  Smoking  \
0          4751   73       0          0               2  22.927749        0   
1          4752   89       0          0               0  26.827681        0   
2          4753   73       0          3               1  17.795882        0   
3          4754   74       1          0               1  33.800817        1   
4          4755   89       0          0               0  20.716974        0   
...         ...  ...     ...        ...             ...        ...      ...   
2144       6895   61       0          0               1  39.121757        0   
2145       6896   75       0          0               2  17.857903        0   
2146       6897   77       0          0               1  15.476479        0   
2147       6898   78       1          3               1  15.299911        0   
2148       6899   72       0          0               2  33.289738        0   

      AlcoholConsum

splitting data into training and testing

In [91]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25,random_state=0)

In [92]:
print(x.shape,x_train.shape,x_test.shape)

(2149, 32) (1611, 32) (538, 32)


In [93]:
print(y_train)

[1 0 0 ... 0 1 0]


In [94]:
print(x_test)

[[6.433e+03 8.800e+01 1.000e+00 ... 1.000e+00 0.000e+00 0.000e+00]
 [6.509e+03 6.200e+01 0.000e+00 ... 0.000e+00 0.000e+00 0.000e+00]
 [5.228e+03 7.700e+01 1.000e+00 ... 1.000e+00 0.000e+00 0.000e+00]
 ...
 [6.731e+03 6.500e+01 0.000e+00 ... 0.000e+00 0.000e+00 0.000e+00]
 [4.817e+03 8.600e+01 0.000e+00 ... 0.000e+00 0.000e+00 1.000e+00]
 [5.384e+03 6.700e+01 1.000e+00 ... 0.000e+00 0.000e+00 0.000e+00]]


data standardization

In [95]:
scaler=StandardScaler()

In [96]:
scaler.fit(x_train)

StandardScaler()

In [97]:
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)

In [98]:
print(x_train)

[[-0.27834351 -0.46364168 -1.02833422 ... -0.41941913 -0.43466066
  -0.66211242]
 [ 0.86863269  1.42225683 -1.02833422 ... -0.41941913 -0.43466066
  -0.66211242]
 [ 1.5844874   0.42383997 -1.02833422 ...  2.38424984 -0.43466066
  -0.66211242]
 ...
 [-0.5132082  -0.46364168  0.97244649 ... -0.41941913 -0.43466066
  -0.66211242]
 [-0.39738451  0.09103435  0.97244649 ... -0.41941913 -0.43466066
  -0.66211242]
 [ 0.91850122 -1.35112333  0.97244649 ... -0.41941913 -0.43466066
   1.51031754]]


training

In [99]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', 
                                    random_state = 0)
classifier.fit(x_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [100]:
print(classifier.predict(scaler.transform([[4771,82,1,0,36.22309879636211,0,4.19289550965694,6.381502407159495,7.971127068871205,9.521026998926784,0,1,0,0,0,0,120,93,271.84144940568734,84.47888882125085,76.37038996359557,361.24201396686277,8.984758990788695,6.946428266027044,0,1,1.6880245896723012,0,0,0,0,1]])))

[1]


In [101]:
y_pred = classifier.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [1 1]
 [0 0]
 [0 0]]


In [102]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[336   8]
 [ 45 149]]


0.9014869888475836